name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_staging:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.ENV_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Publish to Vercel
        run: >
          vercel deploy
          --token ${{ secrets.VERCEL_TOKEN }}
          -n ${{ vars.VERCEL_PROJECT }}
          --yes
          --prod
          --prebuilt
          --env MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING }}
          --env CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }}
          --env CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
          --env CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
          --env JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: Success
        run: echo "🚀  Deploy successful 🚀 "
